Area                               Start  End    Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            text   0000   ffff =     14. bytes (rel,con,rom,code)

Area                               Start  End    Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             bss   0000   00ff =    256. bytes (rel,con,ram)

